site_name: Nevu UI wiki

theme:
  name: material
  language: en 
  palette:
    - scheme: slate
      primary: dark purple
      accent: light blue
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs 
    - navigation.sections 
    - search.highlight 
    - content.code.copy 
  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GolemBebrov
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nevu-ui/ 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true